services:
  postgres:
    image: postgres:latest
    container_name: postgres-server
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: my_database
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 123456789
    ports:
      - "5050:80"
    depends_on:
      - postgres

  php:
    build:
      context: ./
      dockerfile: DockerFile
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  postgres-data: